version: '3'

services:
  ros2_humble:
    container_name: ros2autodoc
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: 3473f